// This file is generated by Sapper — do not edit it!
export const routes = [
	{ error: '4xx', load: () => import(/* webpackChunkName: "_4xx" */ '../../routes/4xx.html') },
	{ error: '5xx', load: () => import(/* webpackChunkName: "_5xx" */ '../../routes/5xx.html') },
	{ pattern: /^\/?$/, ignore: true },
	{ pattern: /^\/guide\/?$/, ignore: true },
	{ pattern: /^\/guide(?:\/([^\/]+?))?\/?$/, params: match => ({ lang: match[1] }), load: () => import(/* webpackChunkName: "guide_$lang$" */ '../../routes/guide/[lang]/index.html') },
	{ pattern: /^\/repl\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "repl" */ '../../routes/repl/index.html') },
	{ pattern: /^\/api\/examples\/?$/, ignore: true },
	{ pattern: /^\/api\/examples(?:\/([^\/]+?))?\/?$/, ignore: true },
	{ pattern: /^\/api\/guide(?:\/([^\/]+?))?\/?$/, ignore: true }
];

if (module.hot) {
	import('/Users/208311/Development/ROLLUP/rollupjs.org/node_modules/sapper/sapper-dev-client.js').then(client => {
		client.connect(10000);
	});
}