// This file is generated by Sapper — do not edit it!
import root from '../../routes/_layout.html';
import error from '../../routes/_error.html';

const index = {
	js: () => import('../../routes/index.html'),
	css: "__SAPPER_CSS_PLACEHOLDER:index.html__"
};
const guide_$lang = {
	js: () => import('../../routes/guide/[lang]/index.html'),
	css: "__SAPPER_CSS_PLACEHOLDER:guide/[lang]/index.html__"
};
const guide_$lang_GuideContents = {
	js: () => import('../../routes/guide/[lang]/GuideContents.html'),
	css: "__SAPPER_CSS_PLACEHOLDER:guide/[lang]/GuideContents.html__"
};
const repl = {
	js: () => import('../../routes/repl/index.html'),
	css: "__SAPPER_CSS_PLACEHOLDER:repl/index.html__"
};

export const manifest = {
	ignore: [/^\/guide$/, /^\/guide\/([^\/]+?).json$/, /^\/api\/examples$/, /^\/api\/examples\/([^\/]+?)$/],

	pages: [
		{
			// index.html
			pattern: /^\/?$/,
			parts: [
				{ component: index }
			]
		},

		{
			// guide/[lang]/index.html
			pattern: /^\/guide\/([^\/]+?)\/?$/,
			parts: [
				null,
				null,
				{ component: guide_$lang, params: match => ({ lang: match[1] }) }
			]
		},

		{
			// guide/[lang]/GuideContents.html
			pattern: /^\/guide\/([^\/]+?)\/GuideContents\/?$/,
			parts: [
				null,
				null,
				{ component: guide_$lang_GuideContents, params: match => ({ lang: match[1] }) }
			]
		},

		{
			// repl/index.html
			pattern: /^\/repl\/?$/,
			parts: [
				null,
				{ component: repl }
			]
		}
	],

	root,

	error
};

// this is included for legacy reasons
export const routes = {};

import('/Users/208311/Development/ROLLUP/rollupjs.org/node_modules/sapper/sapper-dev-client.js').then(client => {
	client.connect(10000);
});