// This file is generated by Sapper — do not edit it!
export const timestamp = 1526916475275;

export const assets = [
	"curl.js",
	"favicon.png",
	"fontello/css/fontello.css",
	"fontello/font/fontello.eot",
	"fontello/font/fontello.svg",
	"fontello/font/fontello.ttf",
	"fontello/font/fontello.woff",
	"fonts/Inconsolata/Inconsolata-Bold.woff",
	"fonts/Inconsolata/Inconsolata-Bold.woff2",
	"fonts/Inconsolata/Inconsolata-Regular.ttf",
	"fonts/Inconsolata/Inconsolata-Regular.woff",
	"fonts/Inconsolata/Inconsolata-Regular.woff2",
	"fonts/Inconsolata/OFL.txt",
	"global.css",
	"images/octocat.svg",
	"images/rollup_logomark.svg",
	"images/select-arrow.svg",
	"images/twitter-card.jpg",
	"logo.svg"
];

export const shell = [
	"client/00816e4eb2891a070f19/0.0.js",
	"client/00816e4eb2891a070f19/_4xx._4xx.js",
	"client/00816e4eb2891a070f19/guide_$lang$.guide_$lang$.js",
	"client/00816e4eb2891a070f19/main.js",
	"client/00816e4eb2891a070f19/repl.repl.js",
	"client/00816e4eb2891a070f19/_5xx._5xx.js",
	"client/00816e4eb2891a070f19/1.1.js",
	"client/00816e4eb2891a070f19/2.2.js",
	"client/00816e4eb2891a070f19/vendors~repl.vendors~repl.js",
	"client/guide_$lang$.0b2fa760a853a8254de2.hot-update.js",
	"client/0b2fa760a853a8254de2.hot-update.json"
];

export const routes = [
	
];