// This file is generated by Sapper — do not edit it!
import _4xx0 from '../../routes/4xx.html';
import _5xx0 from '../../routes/5xx.html';
import * as _0 from '../../routes/index.js';
import * as guide0 from '../../routes/guide/index.js';
import guide_$lang$0 from '../../routes/guide/[lang]/index.html';
import repl0 from '../../routes/repl/index.html';
import * as api_examples0 from '../../routes/api/examples/index.js';
import * as api_examples_$id$0 from '../../routes/api/examples/[id].js';
import * as api_guide_$lang$0 from '../../routes/api/guide/[lang].js';

export const routes = [
	{ error: '4xx', handlers: [{ type: 'page', module: _4xx0 }] },
	{ error: '5xx', handlers: [{ type: 'page', module: _5xx0 }] },
	{ id: '_', pattern: /^\/?$/, params: () => ({}), handlers: [{ type: 'route', module: _0 }] },
	{ id: 'guide', pattern: /^\/guide\/?$/, params: () => ({}), handlers: [{ type: 'route', module: guide0 }] },
	{ id: 'guide_$lang$', pattern: /^\/guide(?:\/([^\/]+?))?\/?$/, params: match => ({ lang: match[1] }), handlers: [{ type: 'page', module: guide_$lang$0 }] },
	{ id: 'repl', pattern: /^\/repl\/?$/, params: () => ({}), handlers: [{ type: 'page', module: repl0 }] },
	{ id: 'api_examples', pattern: /^\/api\/examples\/?$/, params: () => ({}), handlers: [{ type: 'route', module: api_examples0 }] },
	{ id: 'api_examples_$id$', pattern: /^\/api\/examples(?:\/([^\/]+?))?\/?$/, params: match => ({ id: match[1] }), handlers: [{ type: 'route', module: api_examples_$id$0 }] },
	{ id: 'api_guide_$lang$', pattern: /^\/api\/guide(?:\/([^\/]+?))?\/?$/, params: match => ({ lang: match[1] }), handlers: [{ type: 'route', module: api_guide_$lang$0 }] }
];