// This file is generated by Sapper — do not edit it!
export const timestamp = 1535919435238;

export const assets = [
	"CNAME",
	"curl.js",
	"favicon.png",
	"fontello/css/fontello.css",
	"fontello/font/fontello.eot",
	"fontello/font/fontello.svg",
	"fontello/font/fontello.ttf",
	"fontello/font/fontello.woff",
	"fonts/Inconsolata/Inconsolata-Bold.woff",
	"fonts/Inconsolata/Inconsolata-Bold.woff2",
	"fonts/Inconsolata/Inconsolata-Regular.ttf",
	"fonts/Inconsolata/Inconsolata-Regular.woff",
	"fonts/Inconsolata/Inconsolata-Regular.woff2",
	"fonts/Inconsolata/OFL.txt",
	"global.css",
	"images/octocat.svg",
	"images/rollup_logomark.svg",
	"images/select-arrow.svg",
	"images/twitter-card.jpg",
	"logo.svg"
];

export const shell = [
	"client/client.1e449462.js",
	"client/chunk.9c6bd1ca.js",
	"client/chunk.840d6aef.js",
	"client/index.f32086ea.js",
	"client/chunk.fcd163b6.js",
	"client/GuideContents.15cb306a.js",
	"client/index.452af494.js",
	"client/index.a82a3f3a.js",
	"client/sapper-dev-client.c1ed07a9.js",
	"client/codemirror.62134d22.js"
];

export const routes = [
	{ pattern: /^\/?$/ },
	{ pattern: /^\/guide\/([^\/]+?)\/?$/ },
	{ pattern: /^\/guide\/([^\/]+?)\/GuideContents\/?$/ },
	{ pattern: /^\/repl\/?$/ }
];