// This file is generated by Sapper — do not edit it!
import * as route_guide from '../../routes/guide/index.js';
import * as route_guide_$lang_json from '../../routes/guide/[lang]/index.json.js';
import * as route_api_examples from '../../routes/api/examples/index.js';
import * as route_api_examples_$id from '../../routes/api/examples/[id].js';
import index from '../../routes/index.html';
import guide_$lang from '../../routes/guide/[lang]/index.html';
import guide_$lang_GuideContents from '../../routes/guide/[lang]/GuideContents.html';
import repl from '../../routes/repl/index.html';
import root from '../../routes/_layout.html';
import error from '../../routes/_error.html';

export const manifest = {
	server_routes: [
		{
			// guide/index.js
			pattern: /^\/guide$/,
			handlers: route_guide,
			params: () => ({})
		},

		{
			// guide/[lang]/index.json.js
			pattern: /^\/guide\/([^\/]+?).json$/,
			handlers: route_guide_$lang_json,
			params: match => ({ lang: match[1] })
		},

		{
			// api/examples/index.js
			pattern: /^\/api\/examples$/,
			handlers: route_api_examples,
			params: () => ({})
		},

		{
			// api/examples/[id].js
			pattern: /^\/api\/examples\/([^\/]+?)$/,
			handlers: route_api_examples_$id,
			params: match => ({ id: match[1] })
		}
	],

	pages: [
		{
			// index.html
			pattern: /^\/?$/,
			parts: [
				{ name: "index", file: "index.html", component: index }
			]
		},

		{
			// guide/[lang]/index.html
			pattern: /^\/guide\/([^\/]+?)\/?$/,
			parts: [
				null,
				null,
				{ name: "guide_$lang", file: "guide/[lang]/index.html", component: guide_$lang, params: match => ({ lang: match[1] }) }
			]
		},

		{
			// guide/[lang]/GuideContents.html
			pattern: /^\/guide\/([^\/]+?)\/GuideContents\/?$/,
			parts: [
				null,
				null,
				{ name: "guide_$lang_GuideContents", file: "guide/[lang]/GuideContents.html", component: guide_$lang_GuideContents, params: match => ({ lang: match[1] }) }
			]
		},

		{
			// repl/index.html
			pattern: /^\/repl\/?$/,
			parts: [
				null,
				{ name: "repl", file: "repl/index.html", component: repl }
			]
		}
	],

	root,

	error
};

// this is included for legacy reasons
export const routes = {};